debug: false
spring:
  application:
    name: user

  datasource:
    url: jdbc:postgresql://localhost:5435/ms-user-ms
    username: postgres-user
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  rabbitmq:
    # https://www.cloudamqp.com/ - free RabbitMQ hosting service para testes
    addresses: amqps://chameleon.lmq.cloudamqp.com
    username: xcwuwyhw
    password: 1hYt_eCGTVjNxS7kdKZJDs9LOrf4qU6c
    virtual-host: xcwuwyhw

server:
  port: 8081