spring:
  application:
    name: mail

  datasource:
    url: jdbc:postgresql://localhost:5433/ms-mail-ms
    username: postgres-mail
    password: postgres-password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    # https://www.cloudamqp.com/ - free RabbitMQ hosting service para testes
    addresses: amqps://chameleon.lmq.cloudamqp.com
    username: xcwuwyhw
    password: 1hYt_eCGTVjNxS7kdKZJDs9LOrf4qU6c
    virtual-host: xcwuwyhw

server:
  port: 8080